'use strict';

const ERROR_CODES = {
  'MOVED_PERMANENTLY': 301,
  'SEE_OTHER': 303,
  'NOT_MODIFIED': 304,
  'TEMPORARY_REDIRECT': 307,
  'BAD_REQUEST': 400,
  'AUTHORIZATION_REQUIRED': 401,
  'PAYMENT_REQUIRED': 402,
  'FORBIDDEN': 403,
  'NOT_FOUND': 404,
  'METHOD_NOT_ALLOWED': 405,
  'CONFLICT': 409,
  'GONE': 410,
  'PRECONDITION_FAILED': 412,
  'REQUEST_ENTITY_TOO_LARGE': 413,
  'REQUESTED_RANGE_NOT_SATISFIABLE': 416,
  'EXPECTATION_FAILED': 417,
  'INVALID_PARAMETERS': 422,
  'PRECONDITION_REQUIRED': 428,
  'TOO_MANY_REQUESTS': 429,
  'INTERNAL_SERVER_ERROR': 500,
  'NOT_IMPLEMENTED': 501,
  'SERVICE_UNAVAILABLE': 503,
};

module.exports = ERROR_CODES;
